[tools]
meson = "latest"
ninja = "latest"
pipx = "latest"
"github:llvm/llvm-project" = { version = "22.1.1", version_prefix = "llvmorg-", bin = ["bin/clang-tidy", "bin/clang-format", "bin/clang"]}
just = "latest"


[env]
# This magic line tells mise to create and use a venv automatically
# It creates a folder called '.venv' in your project
_.python.venv = ".venv"
