name: CI Checklist

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    container:
      image: ./Dockerfile
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Linter
        run: just lint

      - name: Run Tests
        run: just test

      - name: Run Release Build
        run: just release

  deploy:
    runs-on: ubuntu-latest
    container:
      image: ./Dockerfile

    needs: integration

    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Release Build
        run: just release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/gamu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
